// @generated by scripts/generate-protocol.mjs. Do not edit.

pub const ABI_VERSION: u16 = 23;
pub const MINIMUM_READABLE_ABI_VERSION: u16 = 4;
pub const PROTOCOL_ALIGNMENT: usize = 4;
pub const STREAM_HEADER_BYTES: usize = 16;
pub const INSTRUCTION_HEADER_BYTES: usize = 4;
pub const INSTRUCTION_FLAG_OPTIONAL: u8 = 1;
pub const INSTRUCTION_FLAG_MASK: u8 = 1;
pub const INSTRUCTION_LENGTH_ESCAPE: u16 = 65535;
pub const RECORD_HEADER_BYTES: usize = 8;
pub const NODE_ID_INDEX_BITS: u32 = 20;
pub const NODE_ID_GENERATION_BITS: u32 = 12;
pub const NULL_NODE_ID: u32 = 4294967295;
pub const MUTATION_MAGIC: u32 = 1297108804;
pub const INPUT_MAGIC: u32 = 1229999940;
pub const DISPLAY_LIST_MAGIC: u32 = 1146113860;
pub const GLYPH_RESOURCES_MAGIC: u32 = 1196445508;
pub const SYSTEM_TEXT_METRICS_MAGIC: u32 = 1414549316;
pub const RECORDING_MAGIC: u32 = 1380994884;
pub const MAX_MUTATION_BYTES: usize = 16777216;
pub const MAX_INPUT_BYTES: usize = 16777216;
pub const MAX_DISPLAY_LIST_BYTES: usize = 33554432;
pub const MAX_GLYPH_RESOURCES_BYTES: usize = 16777216;
pub const MAX_SYSTEM_TEXT_METRICS_BYTES: usize = 8388608;
pub const MAX_RECORDING_BYTES: usize = 67108864;
pub const MAX_RESOURCE_BYTES: usize = 8388608;
pub const MAX_MUTATION_INSTRUCTIONS: u32 = 262144;
pub const MAX_INPUT_INSTRUCTIONS: u32 = 262144;
pub const MAX_DISPLAY_INSTRUCTIONS: u32 = 1048576;
pub const MAX_GLYPH_RESOURCE_INSTRUCTIONS: u32 = 262144;
pub const MAX_SYSTEM_TEXT_METRIC_INSTRUCTIONS: u32 = 262144;
pub const MAX_GLYPH_BITMAP_PIXELS: usize = 16777216;
pub const MAX_SYSTEM_TEXT_LINES: u32 = 1048576;
pub const MAX_SYSTEM_TEXT_ADVANCES: u32 = 1048576;
pub const MAX_WORD_BOUNDARIES: u32 = 262144;
pub const MAX_RECORDING_RECORDS: u32 = 1048576;
pub const MAX_VIRTUAL_ITEMS: u32 = 4000000;
pub const MAX_STYLED_RUNS: u32 = 65536;
pub const MAX_KEYBOARD_CODE_ID: u16 = 109;
pub const MAX_KEYBOARD_KEY_NAME_ID: u16 = 51;
pub const VIRTUAL_REFILL_VERSION: u32 = 1;
pub const VIRTUAL_REFILL_HEADER_WORDS: usize = 2;
pub const VIRTUAL_REFILL_RECORD_WORDS: usize = 3;
pub const VIRTUAL_REFILL_HEADER_VERSION_INDEX: usize = 0;
pub const VIRTUAL_REFILL_HEADER_REQUEST_COUNT_INDEX: usize = 1;
pub const VIRTUAL_REFILL_RECORD_NODE_ID_INDEX: usize = 0;
pub const VIRTUAL_REFILL_RECORD_START_INDEX: usize = 1;
pub const VIRTUAL_REFILL_RECORD_END_INDEX: usize = 2;
pub const GLYPH_BITMAP_FIXED_BYTES: Option<usize> = None;
pub const GLYPH_BITMAP_MINIMUM_BYTES: usize = 28;
pub const GLYPH_BITMAP_GLYPH_ID_OFFSET: usize = 0;
pub const GLYPH_BITMAP_LEFT_OFFSET: usize = 4;
pub const GLYPH_BITMAP_TOP_OFFSET: usize = 8;
pub const GLYPH_BITMAP_WIDTH_OFFSET: usize = 12;
pub const GLYPH_BITMAP_HEIGHT_OFFSET: usize = 16;
pub const GLYPH_BITMAP_DEVICE_PIXEL_RATIO_OFFSET: usize = 20;
pub const GLYPH_BITMAP_DATA_BYTES_OFFSET: usize = 24;
pub const GLYPH_BITMAP_DATA_OFFSET: usize = 28;
pub const GLYPH_PLACEMENT_FIXED_BYTES: Option<usize> = Some(12);
pub const GLYPH_PLACEMENT_MINIMUM_BYTES: usize = 12;
pub const GLYPH_PLACEMENT_BITMAP_INDEX_OFFSET: usize = 0;
pub const GLYPH_PLACEMENT_X_OFFSET: usize = 4;
pub const GLYPH_PLACEMENT_Y_OFFSET: usize = 8;
pub const STYLED_RUN_FIXED_BYTES: Option<usize> = Some(24);
pub const STYLED_RUN_MINIMUM_BYTES: usize = 24;
pub const STYLED_RUN_UTF8_START_OFFSET: usize = 0;
pub const STYLED_RUN_UTF8_LENGTH_OFFSET: usize = 4;
pub const STYLED_RUN_STYLE_ID_OFFSET: usize = 8;
pub const STYLED_RUN_FONT_ID_OFFSET: usize = 12;
pub const STYLED_RUN_FLAGS_OFFSET: usize = 16;
pub const STYLED_RUN_RESERVED_OFFSET: usize = 20;
pub const STYLED_RUN_FLAG_ATOMIC: u32 = 1;
pub const FRAME_DIAGNOSTICS_VERSION: u32 = 10;
pub const FRAME_DIAGNOSTICS_WORDS: usize = 45;
pub const FRAME_DIAGNOSTICS_VERSION_INDEX: usize = 0;
pub const FRAME_DIAGNOSTICS_FRAME_SEQ_INDEX: usize = 1;
pub const FRAME_DIAGNOSTICS_SCENE_NODES_INDEX: usize = 2;
pub const FRAME_DIAGNOSTICS_DIRTY_LAYOUT_NODES_INDEX: usize = 3;
pub const FRAME_DIAGNOSTICS_DIRTY_PAINT_NODES_INDEX: usize = 4;
pub const FRAME_DIAGNOSTICS_DIRTY_PAINT_SELF_NODES_INDEX: usize = 5;
pub const FRAME_DIAGNOSTICS_DIRTY_HIT_NODES_INDEX: usize = 6;
pub const FRAME_DIAGNOSTICS_DIRTY_SEMANTICS_NODES_INDEX: usize = 7;
pub const FRAME_DIAGNOSTICS_LAYOUT_CHANGED_NODES_INDEX: usize = 8;
pub const FRAME_DIAGNOSTICS_LAYOUT_VISITED_NODES_INDEX: usize = 9;
pub const FRAME_DIAGNOSTICS_DISPLAY_COMMANDS_INDEX: usize = 10;
pub const FRAME_DIAGNOSTICS_PAINT_REBUILT_INDEX: usize = 11;
pub const FRAME_DIAGNOSTICS_PICTURE_BUILDS_INDEX: usize = 12;
pub const FRAME_DIAGNOSTICS_PICTURE_CACHE_HITS_INDEX: usize = 13;
pub const FRAME_DIAGNOSTICS_PICTURE_SUBTREE_BUILDS_INDEX: usize = 14;
pub const FRAME_DIAGNOSTICS_PICTURE_SUBTREE_CACHE_HITS_INDEX: usize = 15;
pub const FRAME_DIAGNOSTICS_OVER_INVALIDATED_FRAMES_INDEX: usize = 16;
pub const FRAME_DIAGNOSTICS_PICTURE_HASH_LOW_INDEX: usize = 17;
pub const FRAME_DIAGNOSTICS_PICTURE_HASH_HIGH_INDEX: usize = 18;
pub const FRAME_DIAGNOSTICS_VISIBLE_PLACEHOLDERS_INDEX: usize = 19;
pub const FRAME_DIAGNOSTICS_VIRTUAL_VISIBLE_START_INDEX: usize = 20;
pub const FRAME_DIAGNOSTICS_VIRTUAL_VISIBLE_END_INDEX: usize = 21;
pub const FRAME_DIAGNOSTICS_VIRTUAL_MATERIALIZED_START_INDEX: usize = 22;
pub const FRAME_DIAGNOSTICS_VIRTUAL_MATERIALIZED_END_INDEX: usize = 23;
pub const FRAME_DIAGNOSTICS_SKIPPED_INSTRUCTIONS_INDEX: usize = 24;
pub const FRAME_DIAGNOSTICS_PRODUCER_ABI_VERSION_INDEX: usize = 25;
pub const FRAME_DIAGNOSTICS_INTERACTION_STATE_CHANGES_INDEX: usize = 26;
pub const FRAME_DIAGNOSTICS_ANIMATION_ACTIVE_INDEX: usize = 27;
pub const FRAME_DIAGNOSTICS_ANIMATION_PHASE_BEFORE_INDEX: usize = 28;
pub const FRAME_DIAGNOSTICS_ANIMATION_PHASE_ACTIVE_INDEX: usize = 29;
pub const FRAME_DIAGNOSTICS_ANIMATION_PHASE_AFTER_INDEX: usize = 30;
pub const FRAME_DIAGNOSTICS_ANIMATION_STARTS_INDEX: usize = 31;
pub const FRAME_DIAGNOSTICS_ANIMATION_RETARGETS_INDEX: usize = 32;
pub const FRAME_DIAGNOSTICS_ANIMATION_CANCELS_INDEX: usize = 33;
pub const FRAME_DIAGNOSTICS_ANIMATION_SAMPLED_FRAMES_INDEX: usize = 34;
pub const FRAME_DIAGNOSTICS_ANIMATION_PRESENTATION_CHANGES_INDEX: usize = 35;
pub const FRAME_DIAGNOSTICS_ANIMATION_LAYOUT_NODES_INDEX: usize = 36;
pub const FRAME_DIAGNOSTICS_ANIMATION_RETAINED_BYTES_INDEX: usize = 37;
pub const FRAME_DIAGNOSTICS_PICTURE_DEFINES_INDEX: usize = 38;
pub const FRAME_DIAGNOSTICS_PICTURE_RELEASES_INDEX: usize = 39;
pub const FRAME_DIAGNOSTICS_PICTURE_RESIDENT_COUNT_INDEX: usize = 40;
pub const FRAME_DIAGNOSTICS_PICTURE_RESIDENT_BYTES_INDEX: usize = 41;
pub const FRAME_DIAGNOSTICS_PICTURE_RESOURCE_BYTES_INDEX: usize = 42;
pub const FRAME_DIAGNOSTICS_PICTURE_BUDGET_FALLBACKS_INDEX: usize = 43;
pub const FRAME_DIAGNOSTICS_OBSERVE_GEOMETRY_REJECTED_INDEX: usize = 44;
pub const RESOURCE_ENCODING_VERSION: u8 = 1;
pub const SOLID_PAINT_RESOURCE_VARIANT: u8 = 1;
pub const SOLID_PAINT_RESOURCE_FIXED_BYTES: Option<usize> = Some(8);
pub const SOLID_PAINT_RESOURCE_MINIMUM_BYTES: usize = 8;
pub const SOLID_PAINT_VERSION_OFFSET: usize = 0;
pub const SOLID_PAINT_VARIANT_OFFSET: usize = 1;
pub const SOLID_PAINT_RED_OFFSET: usize = 4;
pub const SOLID_PAINT_GREEN_OFFSET: usize = 5;
pub const SOLID_PAINT_BLUE_OFFSET: usize = 6;
pub const SOLID_PAINT_ALPHA_OFFSET: usize = 7;
pub const TEXT_STYLE_RESOURCE_VARIANT: u8 = 1;
pub const TEXT_STYLE_RESOURCE_FIXED_BYTES: Option<usize> = None;
pub const TEXT_STYLE_RESOURCE_MINIMUM_BYTES: usize = 24;
pub const TEXT_STYLE_VERSION_OFFSET: usize = 0;
pub const TEXT_STYLE_VARIANT_OFFSET: usize = 1;
pub const TEXT_STYLE_PAINT_ID_OFFSET: usize = 4;
pub const TEXT_STYLE_FONT_SIZE_OFFSET: usize = 8;
pub const TEXT_STYLE_LINE_HEIGHT_OFFSET: usize = 12;
pub const TEXT_STYLE_WEIGHT_OFFSET: usize = 16;
pub const TEXT_STYLE_FAMILY_BYTES_OFFSET: usize = 20;
pub const TEXT_STYLE_FAMILY_OFFSET: usize = 24;
pub const TEXT_STYLE_V2_RESOURCE_VARIANT: u8 = 2;
pub const TEXT_STYLE_V2_RESOURCE_FIXED_BYTES: Option<usize> = None;
pub const TEXT_STYLE_V2_RESOURCE_MINIMUM_BYTES: usize = 28;
pub const TEXT_STYLE_V2_VERSION_OFFSET: usize = 0;
pub const TEXT_STYLE_V2_VARIANT_OFFSET: usize = 1;
pub const TEXT_STYLE_V2_FONT_STYLE_OFFSET: usize = 2;
pub const TEXT_STYLE_V2_TEXT_ALIGN_OFFSET: usize = 3;
pub const TEXT_STYLE_V2_PAINT_ID_OFFSET: usize = 4;
pub const TEXT_STYLE_V2_FONT_SIZE_OFFSET: usize = 8;
pub const TEXT_STYLE_V2_LINE_HEIGHT_OFFSET: usize = 12;
pub const TEXT_STYLE_V2_WEIGHT_OFFSET: usize = 16;
pub const TEXT_STYLE_V2_WHITE_SPACE_OFFSET: usize = 18;
pub const TEXT_STYLE_V2_OVERFLOW_WRAP_OFFSET: usize = 19;
pub const TEXT_STYLE_V2_TEXT_OVERFLOW_OFFSET: usize = 20;
pub const TEXT_STYLE_V2_RESERVED_OFFSET: usize = 21;
pub const TEXT_STYLE_V2_FAMILY_BYTES_OFFSET: usize = 24;
pub const TEXT_STYLE_V2_FAMILY_OFFSET: usize = 28;
pub const SFNT_FONT_RESOURCE_VARIANT: u8 = 1;
pub const SFNT_FONT_RESOURCE_FIXED_BYTES: Option<usize> = None;
pub const SFNT_FONT_RESOURCE_MINIMUM_BYTES: usize = 12;
pub const SFNT_FONT_VERSION_OFFSET: usize = 0;
pub const SFNT_FONT_VARIANT_OFFSET: usize = 1;
pub const SFNT_FONT_FACE_INDEX_OFFSET: usize = 4;
pub const SFNT_FONT_DATA_BYTES_OFFSET: usize = 8;
pub const SFNT_FONT_DATA_OFFSET: usize = 12;
pub const PATH_RESOURCE_VARIANT: u8 = 1;
pub const PATH_RESOURCE_FIXED_BYTES: Option<usize> = None;
pub const PATH_RESOURCE_MINIMUM_BYTES: usize = 28;
pub const PATH_VERSION_OFFSET: usize = 0;
pub const PATH_VARIANT_OFFSET: usize = 1;
pub const PATH_FILL_RULE_OFFSET: usize = 2;
pub const PATH_RESERVED_OFFSET: usize = 3;
pub const PATH_VERB_COUNT_OFFSET: usize = 4;
pub const PATH_POINT_COUNT_OFFSET: usize = 8;
pub const PATH_VIEW_BOX_X_OFFSET: usize = 12;
pub const PATH_VIEW_BOX_Y_OFFSET: usize = 16;
pub const PATH_VIEW_BOX_WIDTH_OFFSET: usize = 20;
pub const PATH_VIEW_BOX_HEIGHT_OFFSET: usize = 24;
pub const PATH_PAYLOAD_OFFSET: usize = 28;
pub const AFFINE_RESOURCE_VARIANT: u8 = 1;
pub const AFFINE_RESOURCE_FIXED_BYTES: Option<usize> = Some(28);
pub const AFFINE_RESOURCE_MINIMUM_BYTES: usize = 28;
pub const AFFINE_VERSION_OFFSET: usize = 0;
pub const AFFINE_VARIANT_OFFSET: usize = 1;
pub const AFFINE_A_OFFSET: usize = 4;
pub const AFFINE_B_OFFSET: usize = 8;
pub const AFFINE_C_OFFSET: usize = 12;
pub const AFFINE_D_OFFSET: usize = 16;
pub const AFFINE_E_OFFSET: usize = 20;
pub const AFFINE_F_OFFSET: usize = 24;
pub const IMAGE_BITMAP_RESOURCE_VARIANT: u8 = 1;
pub const IMAGE_BITMAP_RESOURCE_FIXED_BYTES: Option<usize> = None;
pub const IMAGE_BITMAP_RESOURCE_MINIMUM_BYTES: usize = 16;
pub const IMAGE_BITMAP_VERSION_OFFSET: usize = 0;
pub const IMAGE_BITMAP_VARIANT_OFFSET: usize = 1;
pub const IMAGE_BITMAP_WIDTH_OFFSET: usize = 4;
pub const IMAGE_BITMAP_HEIGHT_OFFSET: usize = 8;
pub const IMAGE_BITMAP_PIXEL_BYTES_OFFSET: usize = 12;
pub const IMAGE_BITMAP_PIXELS_OFFSET: usize = 16;
pub const VIDEO_FRAME_RESOURCE_VARIANT: u8 = 1;
pub const VIDEO_FRAME_RESOURCE_FIXED_BYTES: Option<usize> = None;
pub const VIDEO_FRAME_RESOURCE_MINIMUM_BYTES: usize = 16;
pub const VIDEO_FRAME_VERSION_OFFSET: usize = 0;
pub const VIDEO_FRAME_VARIANT_OFFSET: usize = 1;
pub const VIDEO_FRAME_WIDTH_OFFSET: usize = 4;
pub const VIDEO_FRAME_HEIGHT_OFFSET: usize = 8;
pub const VIDEO_FRAME_POSTER_PIXEL_BYTES_OFFSET: usize = 12;
pub const VIDEO_FRAME_POSTER_PIXELS_OFFSET: usize = 16;
pub const COMPUTED_STYLE_RESOURCE_VARIANT: u8 = 1;
pub const COMPUTED_STYLE_RESOURCE_FIXED_BYTES: Option<usize> = None;
pub const COMPUTED_STYLE_RESOURCE_MINIMUM_BYTES: usize = 16;
pub const COMPUTED_STYLE_VERSION_OFFSET: usize = 0;
pub const COMPUTED_STYLE_VARIANT_OFFSET: usize = 1;
pub const COMPUTED_STYLE_FEATURE_BITS_OFFSET: usize = 4;
pub const COMPUTED_STYLE_ENTRY_COUNT_OFFSET: usize = 8;
pub const COMPUTED_STYLE_PAYLOAD_BYTES_OFFSET: usize = 12;
pub const COMPUTED_STYLE_PAYLOAD_OFFSET: usize = 16;
pub const STYLED_RUNS_RESOURCE_VARIANT: u8 = 1;
pub const STYLED_RUNS_RESOURCE_FIXED_BYTES: Option<usize> = None;
pub const STYLED_RUNS_RESOURCE_MINIMUM_BYTES: usize = 8;
pub const STYLED_RUNS_VERSION_OFFSET: usize = 0;
pub const STYLED_RUNS_VARIANT_OFFSET: usize = 1;
pub const STYLED_RUNS_RUN_COUNT_OFFSET: usize = 4;
pub const STYLED_RUNS_RUNS_OFFSET: usize = 8;

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum RecordingRecordKind {
    Mutation = 1,
    Input = 2,
    SystemTextMetrics = 3,
    AnimationFrame = 4,
}

impl RecordingRecordKind {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::Mutation),
            2 => Some(Self::Input),
            3 => Some(Self::SystemTextMetrics),
            4 => Some(Self::AnimationFrame),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum VirtualAxis {
    X = 0,
    Y = 1,
}

impl VirtualAxis {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            0 => Some(Self::X),
            1 => Some(Self::Y),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum MutationOpcode {
    CreateNode = 1,
    RemoveNode = 2,
    Reparent = 3,
    SetF32 = 16,
    SetVec4 = 17,
    SetRef = 18,
    SetFlags = 19,
    ClearProp = 20,
    SetTextRun = 32,
    SetRichText = 33,
    DefineResource = 48,
    ReleaseResource = 49,
    ScrollTo = 64,
    ConfigureVirtualList = 65,
    SetVirtualItem = 66,
    ConfigureEditable = 80,
    ObserveGeometry = 96,
    Commit = 240,
}

impl MutationOpcode {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::CreateNode),
            2 => Some(Self::RemoveNode),
            3 => Some(Self::Reparent),
            16 => Some(Self::SetF32),
            17 => Some(Self::SetVec4),
            18 => Some(Self::SetRef),
            19 => Some(Self::SetFlags),
            20 => Some(Self::ClearProp),
            32 => Some(Self::SetTextRun),
            33 => Some(Self::SetRichText),
            48 => Some(Self::DefineResource),
            49 => Some(Self::ReleaseResource),
            64 => Some(Self::ScrollTo),
            65 => Some(Self::ConfigureVirtualList),
            66 => Some(Self::SetVirtualItem),
            80 => Some(Self::ConfigureEditable),
            96 => Some(Self::ObserveGeometry),
            240 => Some(Self::Commit),
            _ => None,
        }
    }
}

impl MutationOpcode {
    #[must_use]
    pub const fn fixed_bytes(self) -> Option<usize> {
        match self {
            Self::CreateNode => Some(20),
            Self::RemoveNode => Some(8),
            Self::Reparent => Some(16),
            Self::SetF32 => Some(16),
            Self::SetVec4 => Some(28),
            Self::SetRef => Some(16),
            Self::SetFlags => Some(16),
            Self::ClearProp => Some(12),
            Self::SetTextRun => Some(16),
            Self::SetRichText => Some(20),
            Self::DefineResource => None,
            Self::ReleaseResource => Some(8),
            Self::ScrollTo => Some(20),
            Self::ConfigureVirtualList => Some(32),
            Self::SetVirtualItem => Some(12),
            Self::ConfigureEditable => Some(24),
            Self::ObserveGeometry => Some(12),
            Self::Commit => Some(8),
        }
    }

    #[must_use]
    pub const fn minimum_bytes(self) -> usize {
        match self {
            Self::CreateNode => 20,
            Self::RemoveNode => 8,
            Self::Reparent => 16,
            Self::SetF32 => 16,
            Self::SetVec4 => 28,
            Self::SetRef => 16,
            Self::SetFlags => 16,
            Self::ClearProp => 12,
            Self::SetTextRun => 16,
            Self::SetRichText => 20,
            Self::DefineResource => 16,
            Self::ReleaseResource => 8,
            Self::ScrollTo => 20,
            Self::ConfigureVirtualList => 32,
            Self::SetVirtualItem => 12,
            Self::ConfigureEditable => 24,
            Self::ObserveGeometry => 12,
            Self::Commit => 8,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum InputOpcode {
    Replace = 1,
    Insert = 2,
    DeleteBackward = 3,
    DeleteForward = 4,
    SetSelection = 5,
    BeginComposition = 6,
    UpdateComposition = 7,
    CommitComposition = 8,
    CancelComposition = 9,
    Undo = 10,
    Redo = 11,
    FocusEditable = 12,
    BlurEditable = 13,
    RequestCharacterBounds = 14,
    PlaceCaret = 15,
    SetWordBoundaries = 17,
    MoveCaret = 16,
    ScrollBegin = 32,
    ScrollDelta = 33,
    ScrollEnd = 34,
    ScrollCancel = 35,
    SetScrollVelocity = 36,
    ScrollTo = 37,
    ScrollBy = 38,
    DispatchEvent = 48,
    SetPointerCapture = 49,
    ReleasePointerCapture = 50,
    FocusNode = 51,
    BlurNode = 52,
    ResetInteraction = 53,
    DispatchKeyEvent = 54,
    Commit = 240,
}

impl InputOpcode {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::Replace),
            2 => Some(Self::Insert),
            3 => Some(Self::DeleteBackward),
            4 => Some(Self::DeleteForward),
            5 => Some(Self::SetSelection),
            6 => Some(Self::BeginComposition),
            7 => Some(Self::UpdateComposition),
            8 => Some(Self::CommitComposition),
            9 => Some(Self::CancelComposition),
            10 => Some(Self::Undo),
            11 => Some(Self::Redo),
            12 => Some(Self::FocusEditable),
            13 => Some(Self::BlurEditable),
            14 => Some(Self::RequestCharacterBounds),
            15 => Some(Self::PlaceCaret),
            17 => Some(Self::SetWordBoundaries),
            16 => Some(Self::MoveCaret),
            32 => Some(Self::ScrollBegin),
            33 => Some(Self::ScrollDelta),
            34 => Some(Self::ScrollEnd),
            35 => Some(Self::ScrollCancel),
            36 => Some(Self::SetScrollVelocity),
            37 => Some(Self::ScrollTo),
            38 => Some(Self::ScrollBy),
            48 => Some(Self::DispatchEvent),
            49 => Some(Self::SetPointerCapture),
            50 => Some(Self::ReleasePointerCapture),
            51 => Some(Self::FocusNode),
            52 => Some(Self::BlurNode),
            53 => Some(Self::ResetInteraction),
            54 => Some(Self::DispatchKeyEvent),
            240 => Some(Self::Commit),
            _ => None,
        }
    }
}

impl InputOpcode {
    #[must_use]
    pub const fn fixed_bytes(self) -> Option<usize> {
        match self {
            Self::Replace => None,
            Self::Insert => None,
            Self::DeleteBackward => Some(16),
            Self::DeleteForward => Some(16),
            Self::SetSelection => Some(28),
            Self::BeginComposition => Some(16),
            Self::UpdateComposition => None,
            Self::CommitComposition => None,
            Self::CancelComposition => Some(16),
            Self::Undo => Some(16),
            Self::Redo => Some(16),
            Self::FocusEditable => Some(8),
            Self::BlurEditable => Some(8),
            Self::RequestCharacterBounds => Some(16),
            Self::PlaceCaret => Some(20),
            Self::SetWordBoundaries => None,
            Self::MoveCaret => Some(12),
            Self::ScrollBegin => Some(8),
            Self::ScrollDelta => Some(20),
            Self::ScrollEnd => Some(8),
            Self::ScrollCancel => Some(8),
            Self::SetScrollVelocity => Some(16),
            Self::ScrollTo => Some(16),
            Self::ScrollBy => Some(16),
            Self::DispatchEvent => Some(68),
            Self::SetPointerCapture => Some(16),
            Self::ReleasePointerCapture => Some(16),
            Self::FocusNode => Some(16),
            Self::BlurNode => Some(12),
            Self::ResetInteraction => Some(12),
            Self::DispatchKeyEvent => Some(28),
            Self::Commit => Some(8),
        }
    }

    #[must_use]
    pub const fn minimum_bytes(self) -> usize {
        match self {
            Self::Replace => 28,
            Self::Insert => 20,
            Self::DeleteBackward => 16,
            Self::DeleteForward => 16,
            Self::SetSelection => 28,
            Self::BeginComposition => 16,
            Self::UpdateComposition => 20,
            Self::CommitComposition => 24,
            Self::CancelComposition => 16,
            Self::Undo => 16,
            Self::Redo => 16,
            Self::FocusEditable => 8,
            Self::BlurEditable => 8,
            Self::RequestCharacterBounds => 16,
            Self::PlaceCaret => 20,
            Self::SetWordBoundaries => 20,
            Self::MoveCaret => 12,
            Self::ScrollBegin => 8,
            Self::ScrollDelta => 20,
            Self::ScrollEnd => 8,
            Self::ScrollCancel => 8,
            Self::SetScrollVelocity => 16,
            Self::ScrollTo => 16,
            Self::ScrollBy => 16,
            Self::DispatchEvent => 68,
            Self::SetPointerCapture => 16,
            Self::ReleasePointerCapture => 16,
            Self::FocusNode => 16,
            Self::BlurNode => 12,
            Self::ResetInteraction => 12,
            Self::DispatchKeyEvent => 28,
            Self::Commit => 8,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum DisplayOpcode {
    Save = 1,
    Restore = 2,
    Transform = 3,
    ClipRect = 4,
    Alpha = 5,
    FillRect = 16,
    FillRRect = 17,
    FillPath = 18,
    StrokePath = 19,
    DrawGlyphRun = 32,
    DrawTextFallback = 33,
    DrawTextInlineFallback = 36,
    FillPlaceholder = 38,
    FillColorRect = 39,
    FillColorRRect = 40,
    FillColorBorder = 41,
    DrawEditorDecoration = 37,
    FillColorShadow = 42,
    FillColorPath = 43,
    StrokeColorPath = 44,
    DrawImage = 34,
    DrawPicture = 35,
}

impl DisplayOpcode {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::Save),
            2 => Some(Self::Restore),
            3 => Some(Self::Transform),
            4 => Some(Self::ClipRect),
            5 => Some(Self::Alpha),
            16 => Some(Self::FillRect),
            17 => Some(Self::FillRRect),
            18 => Some(Self::FillPath),
            19 => Some(Self::StrokePath),
            32 => Some(Self::DrawGlyphRun),
            33 => Some(Self::DrawTextFallback),
            36 => Some(Self::DrawTextInlineFallback),
            38 => Some(Self::FillPlaceholder),
            39 => Some(Self::FillColorRect),
            40 => Some(Self::FillColorRRect),
            41 => Some(Self::FillColorBorder),
            37 => Some(Self::DrawEditorDecoration),
            42 => Some(Self::FillColorShadow),
            43 => Some(Self::FillColorPath),
            44 => Some(Self::StrokeColorPath),
            34 => Some(Self::DrawImage),
            35 => Some(Self::DrawPicture),
            _ => None,
        }
    }
}

impl DisplayOpcode {
    #[must_use]
    pub const fn fixed_bytes(self) -> Option<usize> {
        match self {
            Self::Save => Some(4),
            Self::Restore => Some(4),
            Self::Transform => Some(28),
            Self::ClipRect => Some(20),
            Self::Alpha => Some(8),
            Self::FillRect => Some(24),
            Self::FillRRect => Some(40),
            Self::FillPath => Some(12),
            Self::StrokePath => Some(24),
            Self::DrawGlyphRun => Some(24),
            Self::DrawTextFallback => Some(20),
            Self::DrawTextInlineFallback => None,
            Self::FillPlaceholder => Some(24),
            Self::FillColorRect => Some(24),
            Self::FillColorRRect => Some(40),
            Self::FillColorBorder => Some(68),
            Self::DrawEditorDecoration => Some(28),
            Self::FillColorShadow => Some(52),
            Self::FillColorPath => Some(12),
            Self::StrokeColorPath => Some(24),
            Self::DrawImage => Some(40),
            Self::DrawPicture => Some(16),
        }
    }

    #[must_use]
    pub const fn minimum_bytes(self) -> usize {
        match self {
            Self::Save => 4,
            Self::Restore => 4,
            Self::Transform => 28,
            Self::ClipRect => 20,
            Self::Alpha => 8,
            Self::FillRect => 24,
            Self::FillRRect => 40,
            Self::FillPath => 12,
            Self::StrokePath => 24,
            Self::DrawGlyphRun => 24,
            Self::DrawTextFallback => 20,
            Self::DrawTextInlineFallback => 20,
            Self::FillPlaceholder => 24,
            Self::FillColorRect => 24,
            Self::FillColorRRect => 40,
            Self::FillColorBorder => 68,
            Self::DrawEditorDecoration => 28,
            Self::FillColorShadow => 52,
            Self::FillColorPath => 12,
            Self::StrokeColorPath => 24,
            Self::DrawImage => 40,
            Self::DrawPicture => 16,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum GlyphResourceOpcode {
    DefineGlyphSpan = 1,
    ReleaseGlyphSpan = 2,
}

impl GlyphResourceOpcode {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::DefineGlyphSpan),
            2 => Some(Self::ReleaseGlyphSpan),
            _ => None,
        }
    }
}

impl GlyphResourceOpcode {
    #[must_use]
    pub const fn fixed_bytes(self) -> Option<usize> {
        match self {
            Self::DefineGlyphSpan => None,
            Self::ReleaseGlyphSpan => Some(8),
        }
    }

    #[must_use]
    pub const fn minimum_bytes(self) -> usize {
        match self {
            Self::DefineGlyphSpan => 24,
            Self::ReleaseGlyphSpan => 8,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum SystemTextMetricOpcode {
    UpsertSystemTextMetric = 1,
    ReleaseSystemTextMetric = 2,
}

impl SystemTextMetricOpcode {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::UpsertSystemTextMetric),
            2 => Some(Self::ReleaseSystemTextMetric),
            _ => None,
        }
    }
}

impl SystemTextMetricOpcode {
    #[must_use]
    pub const fn fixed_bytes(self) -> Option<usize> {
        match self {
            Self::UpsertSystemTextMetric => None,
            Self::ReleaseSystemTextMetric => Some(12),
        }
    }

    #[must_use]
    pub const fn minimum_bytes(self) -> usize {
        match self {
            Self::UpsertSystemTextMetric => 32,
            Self::ReleaseSystemTextMetric => 12,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u16)]
pub enum NodeKind {
    Root = 1,
    Container = 2,
    Text = 3,
    Image = 4,
    EditableText = 5,
    Scroll = 6,
    Video = 7,
}

impl NodeKind {
    #[must_use]
    pub const fn from_u16(value: u16) -> Option<Self> {
        match value {
            1 => Some(Self::Root),
            2 => Some(Self::Container),
            3 => Some(Self::Text),
            4 => Some(Self::Image),
            5 => Some(Self::EditableText),
            6 => Some(Self::Scroll),
            7 => Some(Self::Video),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u16)]
pub enum ResourceKind {
    Utf8String = 1,
    Image = 2,
    Path = 3,
    Font = 4,
    GlyphSpan = 5,
    Paint = 6,
    TextStyle = 7,
    Affine = 8,
    ComputedStyle = 9,
    Animation = 10,
    VideoFrame = 11,
    StyledRuns = 12,
}

impl ResourceKind {
    #[must_use]
    pub const fn from_u16(value: u16) -> Option<Self> {
        match value {
            1 => Some(Self::Utf8String),
            2 => Some(Self::Image),
            3 => Some(Self::Path),
            4 => Some(Self::Font),
            5 => Some(Self::GlyphSpan),
            6 => Some(Self::Paint),
            7 => Some(Self::TextStyle),
            8 => Some(Self::Affine),
            9 => Some(Self::ComputedStyle),
            10 => Some(Self::Animation),
            11 => Some(Self::VideoFrame),
            12 => Some(Self::StyledRuns),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u16)]
pub enum Prop {
    Width = 1,
    Height = 2,
    MinWidth = 3,
    MinHeight = 4,
    MaxWidth = 5,
    MaxHeight = 6,
    Padding = 7,
    Direction = 8,
    Gap = 9,
    Color = 16,
    BackgroundColor = 17,
    Opacity = 18,
    Transform = 19,
    Text = 32,
    FontSize = 33,
    Font = 34,
    Image = 35,
    PathStrokeWidth = 38,
    Path = 37,
    VideoFrame = 36,
    OnTap = 48,
    SemanticRole = 64,
    SemanticLabel = 65,
    SemanticValue = 66,
    ComputedStyle = 80,
    Animation = 81,
}

impl Prop {
    #[must_use]
    pub const fn from_u16(value: u16) -> Option<Self> {
        match value {
            1 => Some(Self::Width),
            2 => Some(Self::Height),
            3 => Some(Self::MinWidth),
            4 => Some(Self::MinHeight),
            5 => Some(Self::MaxWidth),
            6 => Some(Self::MaxHeight),
            7 => Some(Self::Padding),
            8 => Some(Self::Direction),
            9 => Some(Self::Gap),
            16 => Some(Self::Color),
            17 => Some(Self::BackgroundColor),
            18 => Some(Self::Opacity),
            19 => Some(Self::Transform),
            32 => Some(Self::Text),
            33 => Some(Self::FontSize),
            34 => Some(Self::Font),
            35 => Some(Self::Image),
            38 => Some(Self::PathStrokeWidth),
            37 => Some(Self::Path),
            36 => Some(Self::VideoFrame),
            48 => Some(Self::OnTap),
            64 => Some(Self::SemanticRole),
            65 => Some(Self::SemanticLabel),
            66 => Some(Self::SemanticValue),
            80 => Some(Self::ComputedStyle),
            81 => Some(Self::Animation),
            _ => None,
        }
    }
}

impl Prop {
    #[must_use]
    pub const fn invalidation(self) -> Invalidation {
        match self {
            Self::Width => Invalidation::from_bits(3),
            Self::Height => Invalidation::from_bits(3),
            Self::MinWidth => Invalidation::from_bits(3),
            Self::MinHeight => Invalidation::from_bits(3),
            Self::MaxWidth => Invalidation::from_bits(3),
            Self::MaxHeight => Invalidation::from_bits(3),
            Self::Padding => Invalidation::from_bits(3),
            Self::Direction => Invalidation::from_bits(3),
            Self::Gap => Invalidation::from_bits(3),
            Self::Color => Invalidation::from_bits(2),
            Self::BackgroundColor => Invalidation::from_bits(2),
            Self::Opacity => Invalidation::from_bits(4),
            Self::Transform => Invalidation::from_bits(10),
            Self::Text => Invalidation::from_bits(19),
            Self::FontSize => Invalidation::from_bits(3),
            Self::Font => Invalidation::from_bits(3),
            Self::Image => Invalidation::from_bits(3),
            Self::PathStrokeWidth => Invalidation::from_bits(2),
            Self::Path => Invalidation::from_bits(2),
            Self::VideoFrame => Invalidation::from_bits(3),
            Self::OnTap => Invalidation::from_bits(0),
            Self::SemanticRole => Invalidation::from_bits(16),
            Self::SemanticLabel => Invalidation::from_bits(16),
            Self::SemanticValue => Invalidation::from_bits(16),
            Self::ComputedStyle => Invalidation::from_bits(63),
            Self::Animation => Invalidation::from_bits(12),
        }
    }

    #[must_use]
    pub const fn value_type(self) -> PropValueType {
        match self {
            Self::Width => PropValueType::F32,
            Self::Height => PropValueType::F32,
            Self::MinWidth => PropValueType::F32,
            Self::MinHeight => PropValueType::F32,
            Self::MaxWidth => PropValueType::F32,
            Self::MaxHeight => PropValueType::F32,
            Self::Padding => PropValueType::Vec4,
            Self::Direction => PropValueType::F32,
            Self::Gap => PropValueType::F32,
            Self::Color => PropValueType::Ref,
            Self::BackgroundColor => PropValueType::Ref,
            Self::Opacity => PropValueType::F32,
            Self::Transform => PropValueType::Ref,
            Self::Text => PropValueType::Ref,
            Self::FontSize => PropValueType::F32,
            Self::Font => PropValueType::Ref,
            Self::Image => PropValueType::Ref,
            Self::PathStrokeWidth => PropValueType::F32,
            Self::Path => PropValueType::Ref,
            Self::VideoFrame => PropValueType::Ref,
            Self::OnTap => PropValueType::Ref,
            Self::SemanticRole => PropValueType::Ref,
            Self::SemanticLabel => PropValueType::Ref,
            Self::SemanticValue => PropValueType::Ref,
            Self::ComputedStyle => PropValueType::Ref,
            Self::Animation => PropValueType::Ref,
        }
    }

    #[must_use]
    pub const fn resource_kind(self) -> Option<ResourceKind> {
        match self {
            Self::Width => None,
            Self::Height => None,
            Self::MinWidth => None,
            Self::MinHeight => None,
            Self::MaxWidth => None,
            Self::MaxHeight => None,
            Self::Padding => None,
            Self::Direction => None,
            Self::Gap => None,
            Self::Color => Some(ResourceKind::Paint),
            Self::BackgroundColor => Some(ResourceKind::Paint),
            Self::Opacity => None,
            Self::Transform => Some(ResourceKind::Affine),
            Self::Text => Some(ResourceKind::Utf8String),
            Self::FontSize => None,
            Self::Font => Some(ResourceKind::Font),
            Self::Image => Some(ResourceKind::Image),
            Self::PathStrokeWidth => None,
            Self::Path => Some(ResourceKind::Path),
            Self::VideoFrame => Some(ResourceKind::VideoFrame),
            Self::OnTap => None,
            Self::SemanticRole => Some(ResourceKind::Utf8String),
            Self::SemanticLabel => Some(ResourceKind::Utf8String),
            Self::SemanticValue => Some(ResourceKind::Utf8String),
            Self::ComputedStyle => Some(ResourceKind::ComputedStyle),
            Self::Animation => Some(ResourceKind::Animation),
        }
    }
}

pub const PICTURE_RESOURCES_MAGIC: u32 = 1347440452;
pub const MAX_PICTURE_RESOURCES_BYTES: usize = 16777216;
pub const MAX_PICTURE_RESOURCE_INSTRUCTIONS: u32 = 262144;
pub const MAX_PICTURE_RESIDENT_BYTES: usize = 16777216;
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum PictureResourceOpcode {
    DefinePicture = 1,
    ReleasePicture = 2,
}

impl PictureResourceOpcode {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::DefinePicture),
            2 => Some(Self::ReleasePicture),
            _ => None,
        }
    }
}

impl PictureResourceOpcode {
    #[must_use]
    pub const fn fixed_bytes(self) -> Option<usize> {
        match self {
            Self::DefinePicture => None,
            Self::ReleasePicture => Some(8),
        }
    }

    #[must_use]
    pub const fn minimum_bytes(self) -> usize {
        match self {
            Self::DefinePicture => 12,
            Self::ReleasePicture => 8,
        }
    }
}

pub const NON_PASSIVE_REGION_VERSION: u32 = 1;
pub const NON_PASSIVE_REGION_HEADER_WORDS: usize = 2;
pub const NON_PASSIVE_REGION_RECORD_WORDS: usize = 5;
pub const NON_PASSIVE_REGION_HEADER_VERSION_INDEX: usize = 0;
pub const NON_PASSIVE_REGION_HEADER_REGION_COUNT_INDEX: usize = 1;
pub const NON_PASSIVE_REGION_RECORD_FLAGS_INDEX: usize = 0;
pub const NON_PASSIVE_REGION_RECORD_LEFT_BITS_INDEX: usize = 1;
pub const NON_PASSIVE_REGION_RECORD_TOP_BITS_INDEX: usize = 2;
pub const NON_PASSIVE_REGION_RECORD_RIGHT_BITS_INDEX: usize = 3;
pub const NON_PASSIVE_REGION_RECORD_BOTTOM_BITS_INDEX: usize = 4;
pub const EDITING_GEOMETRY_VERSION: u32 = 1;
pub const EDITING_GEOMETRY_HEADER_WORDS: usize = 5;
pub const EDITING_GEOMETRY_RECT_WORDS: usize = 4;
pub const EDITING_GEOMETRY_CHARACTER_WORDS: usize = 6;
pub const EDITING_GEOMETRY_HEADER_VERSION_INDEX: usize = 0;
pub const EDITING_GEOMETRY_HEADER_NODE_ID_INDEX: usize = 1;
pub const EDITING_GEOMETRY_HEADER_SELECTION_START_INDEX: usize = 2;
pub const EDITING_GEOMETRY_HEADER_SELECTION_END_INDEX: usize = 3;
pub const EDITING_GEOMETRY_HEADER_CHARACTER_COUNT_INDEX: usize = 4;
pub const EDITING_GEOMETRY_RECT_LEFT_BITS_INDEX: usize = 0;
pub const EDITING_GEOMETRY_RECT_TOP_BITS_INDEX: usize = 1;
pub const EDITING_GEOMETRY_RECT_WIDTH_BITS_INDEX: usize = 2;
pub const EDITING_GEOMETRY_RECT_HEIGHT_BITS_INDEX: usize = 3;
pub const EDITING_GEOMETRY_CHARACTER_START_INDEX: usize = 0;
pub const EDITING_GEOMETRY_CHARACTER_END_INDEX: usize = 1;
pub const EDITING_GEOMETRY_CHARACTER_LEFT_BITS_INDEX: usize = 2;
pub const EDITING_GEOMETRY_CHARACTER_TOP_BITS_INDEX: usize = 3;
pub const EDITING_GEOMETRY_CHARACTER_WIDTH_BITS_INDEX: usize = 4;
pub const EDITING_GEOMETRY_CHARACTER_HEIGHT_BITS_INDEX: usize = 5;
pub const SEMANTICS_VERSION: u32 = 1;
pub const SEMANTICS_HEADER_WORDS: usize = 2;
pub const SEMANTICS_RECORD_WORDS: usize = 9;
pub const SEMANTICS_HEADER_VERSION_INDEX: usize = 0;
pub const SEMANTICS_HEADER_NODE_COUNT_INDEX: usize = 1;
pub const SEMANTICS_RECORD_NODE_ID_INDEX: usize = 0;
pub const SEMANTICS_RECORD_FLAGS_INDEX: usize = 1;
pub const SEMANTICS_RECORD_LEFT_BITS_INDEX: usize = 2;
pub const SEMANTICS_RECORD_TOP_BITS_INDEX: usize = 3;
pub const SEMANTICS_RECORD_WIDTH_BITS_INDEX: usize = 4;
pub const SEMANTICS_RECORD_HEIGHT_BITS_INDEX: usize = 5;
pub const SEMANTICS_RECORD_ROLE_BYTES_INDEX: usize = 6;
pub const SEMANTICS_RECORD_LABEL_BYTES_INDEX: usize = 7;
pub const SEMANTICS_RECORD_VALUE_BYTES_INDEX: usize = 8;
pub const PAINTED_TEXT_VERSION: u32 = 1;
pub const PAINTED_TEXT_HEADER_WORDS: usize = 3;
pub const PAINTED_TEXT_RECORD_WORDS: usize = 5;
pub const PAINTED_TEXT_HEADER_VERSION_INDEX: usize = 0;
pub const PAINTED_TEXT_HEADER_FLAGS_INDEX: usize = 1;
pub const PAINTED_TEXT_HEADER_RECORD_COUNT_INDEX: usize = 2;
pub const PAINTED_TEXT_RECORD_NODE_ID_INDEX: usize = 0;
pub const PAINTED_TEXT_RECORD_FLAGS_INDEX: usize = 1;
pub const PAINTED_TEXT_RECORD_X_BITS_INDEX: usize = 2;
pub const PAINTED_TEXT_RECORD_Y_BITS_INDEX: usize = 3;
pub const PAINTED_TEXT_RECORD_TEXT_BYTES_INDEX: usize = 4;
pub const PAINTED_TEXT_CHANNEL_MASK: u32 = 3;
pub const PAINTED_TEXT_CHANNEL_SHAPED_RUN: u32 = 0;
pub const PAINTED_TEXT_CHANNEL_SYSTEM_FALLBACK: u32 = 1;
pub const PAINTED_TEXT_CHANNEL_INLINE_FALLBACK: u32 = 2;
pub const PAINTED_TEXT_FLAG_ORIGIN_CLIPPED: u32 = 4;
pub const PAINTED_TEXT_FLAG_UNATTRIBUTED: u32 = 8;
pub const PAINTED_TEXT_HEADER_FLAG_TRUNCATED: u32 = 1;
pub const LAYOUT_GEOMETRY_VERSION: u32 = 1;
pub const LAYOUT_GEOMETRY_HEADER_WORDS: usize = 3;
pub const LAYOUT_GEOMETRY_RECORD_WORDS: usize = 10;
pub const LAYOUT_GEOMETRY_HEADER_VERSION_INDEX: usize = 0;
pub const LAYOUT_GEOMETRY_HEADER_FRAME_SEQ_INDEX: usize = 1;
pub const LAYOUT_GEOMETRY_HEADER_RECORD_COUNT_INDEX: usize = 2;
pub const LAYOUT_GEOMETRY_RECORD_NODE_ID_INDEX: usize = 0;
pub const LAYOUT_GEOMETRY_RECORD_FLAGS_INDEX: usize = 1;
pub const LAYOUT_GEOMETRY_RECORD_OWN_LEFT_BITS_INDEX: usize = 2;
pub const LAYOUT_GEOMETRY_RECORD_OWN_TOP_BITS_INDEX: usize = 3;
pub const LAYOUT_GEOMETRY_RECORD_OWN_WIDTH_BITS_INDEX: usize = 4;
pub const LAYOUT_GEOMETRY_RECORD_OWN_HEIGHT_BITS_INDEX: usize = 5;
pub const LAYOUT_GEOMETRY_RECORD_CLIP_LEFT_BITS_INDEX: usize = 6;
pub const LAYOUT_GEOMETRY_RECORD_CLIP_TOP_BITS_INDEX: usize = 7;
pub const LAYOUT_GEOMETRY_RECORD_CLIP_WIDTH_BITS_INDEX: usize = 8;
pub const LAYOUT_GEOMETRY_RECORD_CLIP_HEIGHT_BITS_INDEX: usize = 9;
pub const MAX_OBSERVED_GEOMETRY_NODES: u32 = 64;
pub const EDIT_TRANSACTIONS_MAGIC: u32 = 1162891076;
pub const MAX_EDIT_TRANSACTIONS_BYTES: usize = 16777216;
pub const MAX_EDIT_TRANSACTION_INSTRUCTIONS: u32 = 262144;
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum EditTransactionOpcode {
    Transaction = 1,
}

impl EditTransactionOpcode {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::Transaction),
            _ => None,
        }
    }
}

impl EditTransactionOpcode {
    #[must_use]
    pub const fn fixed_bytes(self) -> Option<usize> {
        match self {
            Self::Transaction => None,
        }
    }

    #[must_use]
    pub const fn minimum_bytes(self) -> usize {
        match self {
            Self::Transaction => 56,
        }
    }
}

pub const EVENT_TRANSACTIONS_MAGIC: u32 = 1448103748;
pub const MAX_EVENT_TRANSACTIONS_BYTES: usize = 16777216;
pub const MAX_EVENT_TRANSACTION_INSTRUCTIONS: u32 = 262144;
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum EventTransactionOpcode {
    Event = 1,
}

impl EventTransactionOpcode {
    #[must_use]
    pub const fn from_u8(value: u8) -> Option<Self> {
        match value {
            1 => Some(Self::Event),
            _ => None,
        }
    }
}

impl EventTransactionOpcode {
    #[must_use]
    pub const fn fixed_bytes(self) -> Option<usize> {
        match self {
            Self::Event => None,
        }
    }

    #[must_use]
    pub const fn minimum_bytes(self) -> usize {
        match self {
            Self::Event => 92,
        }
    }
}
