// @generated by scripts/generate-protocol.mjs. Do not edit.

export const ABI_VERSION = 25 as const;
export const MINIMUM_READABLE_ABI_VERSION = 4 as const;
export const PROTOCOL_ALIGNMENT = 4 as const;
export const STREAM_HEADER_BYTES = 16 as const;
export const INSTRUCTION_HEADER_BYTES = 4 as const;
export const INSTRUCTION_FLAG_OPTIONAL = 1 as const;
export const INSTRUCTION_FLAG_MASK = 1 as const;
export const INSTRUCTION_LENGTH_ESCAPE = 65535 as const;
export const RECORD_HEADER_BYTES = 8 as const;
export const NODE_ID_INDEX_BITS = 20 as const;
export const NODE_ID_GENERATION_BITS = 12 as const;
export const NULL_NODE_ID = 4294967295 as const;
export const MUTATION_MAGIC = 1297108804 as const;
export const INPUT_MAGIC = 1229999940 as const;
export const DISPLAY_LIST_MAGIC = 1146113860 as const;
export const GLYPH_RESOURCES_MAGIC = 1196445508 as const;
export const SYSTEM_TEXT_METRICS_MAGIC = 1414549316 as const;
export const RECORDING_MAGIC = 1380994884 as const;
export const MAX_MUTATION_BYTES = 16777216 as const;
export const MAX_INPUT_BYTES = 16777216 as const;
export const MAX_DISPLAY_LIST_BYTES = 33554432 as const;
export const MAX_GLYPH_RESOURCES_BYTES = 16777216 as const;
export const MAX_SYSTEM_TEXT_METRICS_BYTES = 8388608 as const;
export const MAX_RECORDING_BYTES = 67108864 as const;
export const MAX_RESOURCE_BYTES = 8388608 as const;
export const MAX_MUTATION_INSTRUCTIONS = 262144 as const;
export const MAX_INPUT_INSTRUCTIONS = 262144 as const;
export const MAX_DISPLAY_INSTRUCTIONS = 1048576 as const;
export const MAX_GLYPH_RESOURCE_INSTRUCTIONS = 262144 as const;
export const MAX_SYSTEM_TEXT_METRIC_INSTRUCTIONS = 262144 as const;
export const MAX_GLYPH_BITMAP_PIXELS = 16777216 as const;
export const MAX_SYSTEM_TEXT_LINES = 1048576 as const;
export const MAX_SYSTEM_TEXT_ADVANCES = 1048576 as const;
export const MAX_WORD_BOUNDARIES = 262144 as const;
export const MAX_RECORDING_RECORDS = 1048576 as const;
export const MAX_VIRTUAL_ITEMS = 4000000 as const;
export const MAX_STYLED_RUNS = 65536 as const;
export const MAX_EDIT_MARK_RUNS = 65536 as const;
export const MAX_EDIT_MAP_SEGMENTS = 65536 as const;
export const MAX_DOCUMENT_BLOCK_KEYS = 65536 as const;
export const VIRTUAL_REFILL_VERSION = 1 as const;
export const VIRTUAL_REFILL_HEADER_WORDS = 2 as const;
export const VIRTUAL_REFILL_RECORD_WORDS = 3 as const;
export const VIRTUAL_REFILL_HEADER_VERSION_INDEX = 0 as const;
export const VIRTUAL_REFILL_HEADER_REQUEST_COUNT_INDEX = 1 as const;
export const VIRTUAL_REFILL_RECORD_NODE_ID_INDEX = 0 as const;
export const VIRTUAL_REFILL_RECORD_START_INDEX = 1 as const;
export const VIRTUAL_REFILL_RECORD_END_INDEX = 2 as const;
export const GLYPH_BITMAP_FIXED_BYTES = null;
export const GLYPH_BITMAP_MINIMUM_BYTES = 28 as const;
export const GLYPH_BITMAP_GLYPH_ID_OFFSET = 0 as const;
export const GLYPH_BITMAP_LEFT_OFFSET = 4 as const;
export const GLYPH_BITMAP_TOP_OFFSET = 8 as const;
export const GLYPH_BITMAP_WIDTH_OFFSET = 12 as const;
export const GLYPH_BITMAP_HEIGHT_OFFSET = 16 as const;
export const GLYPH_BITMAP_DEVICE_PIXEL_RATIO_OFFSET = 20 as const;
export const GLYPH_BITMAP_DATA_BYTES_OFFSET = 24 as const;
export const GLYPH_BITMAP_DATA_OFFSET = 28 as const;
export const GLYPH_PLACEMENT_FIXED_BYTES = 12 as const;
export const GLYPH_PLACEMENT_MINIMUM_BYTES = 12 as const;
export const GLYPH_PLACEMENT_BITMAP_INDEX_OFFSET = 0 as const;
export const GLYPH_PLACEMENT_X_OFFSET = 4 as const;
export const GLYPH_PLACEMENT_Y_OFFSET = 8 as const;
export const STYLED_RUN_FIXED_BYTES = 24 as const;
export const STYLED_RUN_MINIMUM_BYTES = 24 as const;
export const STYLED_RUN_UTF8_START_OFFSET = 0 as const;
export const STYLED_RUN_UTF8_LENGTH_OFFSET = 4 as const;
export const STYLED_RUN_STYLE_ID_OFFSET = 8 as const;
export const STYLED_RUN_FONT_ID_OFFSET = 12 as const;
export const STYLED_RUN_FLAGS_OFFSET = 16 as const;
export const STYLED_RUN_RESERVED_OFFSET = 20 as const;
export const EDIT_MARK_RUN_FIXED_BYTES = 12 as const;
export const EDIT_MARK_RUN_MINIMUM_BYTES = 12 as const;
export const EDIT_MARK_RUN_LENGTH_OFFSET = 0 as const;
export const EDIT_MARK_RUN_STYLE_OFFSET = 4 as const;
export const EDIT_MARK_RUN_FONT_OFFSET = 8 as const;
export const EDIT_MAP_SEGMENT_FIXED_BYTES = 20 as const;
export const EDIT_MAP_SEGMENT_MINIMUM_BYTES = 20 as const;
export const EDIT_MAP_SEGMENT_OLD_START_OFFSET = 0 as const;
export const EDIT_MAP_SEGMENT_OLD_END_OFFSET = 4 as const;
export const EDIT_MAP_SEGMENT_NEW_START_OFFSET = 8 as const;
export const EDIT_MAP_SEGMENT_NEW_END_OFFSET = 12 as const;
export const EDIT_MAP_SEGMENT_FLAGS_OFFSET = 16 as const;
export const EDIT_MAP_SEGMENT_FLAG_KEPT = 1 as const;
export const STYLED_RUN_FLAG_ATOMIC = 1 as const;
export const FRAME_DIAGNOSTICS_VERSION = 11 as const;
export const FRAME_DIAGNOSTICS_WORDS = 47 as const;
export const FRAME_DIAGNOSTICS_VERSION_INDEX = 0 as const;
export const FRAME_DIAGNOSTICS_FRAME_SEQ_INDEX = 1 as const;
export const FRAME_DIAGNOSTICS_SCENE_NODES_INDEX = 2 as const;
export const FRAME_DIAGNOSTICS_DIRTY_LAYOUT_NODES_INDEX = 3 as const;
export const FRAME_DIAGNOSTICS_DIRTY_PAINT_NODES_INDEX = 4 as const;
export const FRAME_DIAGNOSTICS_DIRTY_PAINT_SELF_NODES_INDEX = 5 as const;
export const FRAME_DIAGNOSTICS_DIRTY_HIT_NODES_INDEX = 6 as const;
export const FRAME_DIAGNOSTICS_DIRTY_SEMANTICS_NODES_INDEX = 7 as const;
export const FRAME_DIAGNOSTICS_LAYOUT_CHANGED_NODES_INDEX = 8 as const;
export const FRAME_DIAGNOSTICS_LAYOUT_VISITED_NODES_INDEX = 9 as const;
export const FRAME_DIAGNOSTICS_DISPLAY_COMMANDS_INDEX = 10 as const;
export const FRAME_DIAGNOSTICS_PAINT_REBUILT_INDEX = 11 as const;
export const FRAME_DIAGNOSTICS_PICTURE_BUILDS_INDEX = 12 as const;
export const FRAME_DIAGNOSTICS_PICTURE_CACHE_HITS_INDEX = 13 as const;
export const FRAME_DIAGNOSTICS_PICTURE_SUBTREE_BUILDS_INDEX = 14 as const;
export const FRAME_DIAGNOSTICS_PICTURE_SUBTREE_CACHE_HITS_INDEX = 15 as const;
export const FRAME_DIAGNOSTICS_OVER_INVALIDATED_FRAMES_INDEX = 16 as const;
export const FRAME_DIAGNOSTICS_PICTURE_HASH_LOW_INDEX = 17 as const;
export const FRAME_DIAGNOSTICS_PICTURE_HASH_HIGH_INDEX = 18 as const;
export const FRAME_DIAGNOSTICS_VISIBLE_PLACEHOLDERS_INDEX = 19 as const;
export const FRAME_DIAGNOSTICS_VIRTUAL_VISIBLE_START_INDEX = 20 as const;
export const FRAME_DIAGNOSTICS_VIRTUAL_VISIBLE_END_INDEX = 21 as const;
export const FRAME_DIAGNOSTICS_VIRTUAL_MATERIALIZED_START_INDEX = 22 as const;
export const FRAME_DIAGNOSTICS_VIRTUAL_MATERIALIZED_END_INDEX = 23 as const;
export const FRAME_DIAGNOSTICS_SKIPPED_INSTRUCTIONS_INDEX = 24 as const;
export const FRAME_DIAGNOSTICS_PRODUCER_ABI_VERSION_INDEX = 25 as const;
export const FRAME_DIAGNOSTICS_INTERACTION_STATE_CHANGES_INDEX = 26 as const;
export const FRAME_DIAGNOSTICS_ANIMATION_ACTIVE_INDEX = 27 as const;
export const FRAME_DIAGNOSTICS_ANIMATION_PHASE_BEFORE_INDEX = 28 as const;
export const FRAME_DIAGNOSTICS_ANIMATION_PHASE_ACTIVE_INDEX = 29 as const;
export const FRAME_DIAGNOSTICS_ANIMATION_PHASE_AFTER_INDEX = 30 as const;
export const FRAME_DIAGNOSTICS_ANIMATION_STARTS_INDEX = 31 as const;
export const FRAME_DIAGNOSTICS_ANIMATION_RETARGETS_INDEX = 32 as const;
export const FRAME_DIAGNOSTICS_ANIMATION_CANCELS_INDEX = 33 as const;
export const FRAME_DIAGNOSTICS_ANIMATION_SAMPLED_FRAMES_INDEX = 34 as const;
export const FRAME_DIAGNOSTICS_ANIMATION_PRESENTATION_CHANGES_INDEX = 35 as const;
export const FRAME_DIAGNOSTICS_ANIMATION_LAYOUT_NODES_INDEX = 36 as const;
export const FRAME_DIAGNOSTICS_ANIMATION_RETAINED_BYTES_INDEX = 37 as const;
export const FRAME_DIAGNOSTICS_PICTURE_DEFINES_INDEX = 38 as const;
export const FRAME_DIAGNOSTICS_PICTURE_RELEASES_INDEX = 39 as const;
export const FRAME_DIAGNOSTICS_PICTURE_RESIDENT_COUNT_INDEX = 40 as const;
export const FRAME_DIAGNOSTICS_PICTURE_RESIDENT_BYTES_INDEX = 41 as const;
export const FRAME_DIAGNOSTICS_PICTURE_RESOURCE_BYTES_INDEX = 42 as const;
export const FRAME_DIAGNOSTICS_PICTURE_BUDGET_FALLBACKS_INDEX = 43 as const;
export const FRAME_DIAGNOSTICS_OBSERVE_GEOMETRY_REJECTED_INDEX = 44 as const;
export const FRAME_DIAGNOSTICS_DOCUMENT_STRUCTURE_REQUESTS_INDEX = 45 as const;
export const FRAME_DIAGNOSTICS_DOCUMENT_CORRECTIONS_INDEX = 46 as const;
export const RESOURCE_ENCODING_VERSION = 1 as const;
export const SOLID_PAINT_RESOURCE_VARIANT = 1 as const;
export const SOLID_PAINT_RESOURCE_FIXED_BYTES = 8 as const;
export const SOLID_PAINT_RESOURCE_MINIMUM_BYTES = 8 as const;
export const SOLID_PAINT_VERSION_OFFSET = 0 as const;
export const SOLID_PAINT_VARIANT_OFFSET = 1 as const;
export const SOLID_PAINT_RED_OFFSET = 4 as const;
export const SOLID_PAINT_GREEN_OFFSET = 5 as const;
export const SOLID_PAINT_BLUE_OFFSET = 6 as const;
export const SOLID_PAINT_ALPHA_OFFSET = 7 as const;
export const TEXT_STYLE_RESOURCE_VARIANT = 1 as const;
export const TEXT_STYLE_RESOURCE_FIXED_BYTES = null;
export const TEXT_STYLE_RESOURCE_MINIMUM_BYTES = 24 as const;
export const TEXT_STYLE_VERSION_OFFSET = 0 as const;
export const TEXT_STYLE_VARIANT_OFFSET = 1 as const;
export const TEXT_STYLE_PAINT_ID_OFFSET = 4 as const;
export const TEXT_STYLE_FONT_SIZE_OFFSET = 8 as const;
export const TEXT_STYLE_LINE_HEIGHT_OFFSET = 12 as const;
export const TEXT_STYLE_WEIGHT_OFFSET = 16 as const;
export const TEXT_STYLE_FAMILY_BYTES_OFFSET = 20 as const;
export const TEXT_STYLE_FAMILY_OFFSET = 24 as const;
export const TEXT_STYLE_V2_RESOURCE_VARIANT = 2 as const;
export const TEXT_STYLE_V2_RESOURCE_FIXED_BYTES = null;
export const TEXT_STYLE_V2_RESOURCE_MINIMUM_BYTES = 28 as const;
export const TEXT_STYLE_V2_VERSION_OFFSET = 0 as const;
export const TEXT_STYLE_V2_VARIANT_OFFSET = 1 as const;
export const TEXT_STYLE_V2_FONT_STYLE_OFFSET = 2 as const;
export const TEXT_STYLE_V2_TEXT_ALIGN_OFFSET = 3 as const;
export const TEXT_STYLE_V2_PAINT_ID_OFFSET = 4 as const;
export const TEXT_STYLE_V2_FONT_SIZE_OFFSET = 8 as const;
export const TEXT_STYLE_V2_LINE_HEIGHT_OFFSET = 12 as const;
export const TEXT_STYLE_V2_WEIGHT_OFFSET = 16 as const;
export const TEXT_STYLE_V2_WHITE_SPACE_OFFSET = 18 as const;
export const TEXT_STYLE_V2_OVERFLOW_WRAP_OFFSET = 19 as const;
export const TEXT_STYLE_V2_TEXT_OVERFLOW_OFFSET = 20 as const;
export const TEXT_STYLE_V2_RESERVED_OFFSET = 21 as const;
export const TEXT_STYLE_V2_FAMILY_BYTES_OFFSET = 24 as const;
export const TEXT_STYLE_V2_FAMILY_OFFSET = 28 as const;
export const SFNT_FONT_RESOURCE_VARIANT = 1 as const;
export const SFNT_FONT_RESOURCE_FIXED_BYTES = null;
export const SFNT_FONT_RESOURCE_MINIMUM_BYTES = 12 as const;
export const SFNT_FONT_VERSION_OFFSET = 0 as const;
export const SFNT_FONT_VARIANT_OFFSET = 1 as const;
export const SFNT_FONT_FACE_INDEX_OFFSET = 4 as const;
export const SFNT_FONT_DATA_BYTES_OFFSET = 8 as const;
export const SFNT_FONT_DATA_OFFSET = 12 as const;
export const PATH_RESOURCE_VARIANT = 1 as const;
export const PATH_RESOURCE_FIXED_BYTES = null;
export const PATH_RESOURCE_MINIMUM_BYTES = 28 as const;
export const PATH_VERSION_OFFSET = 0 as const;
export const PATH_VARIANT_OFFSET = 1 as const;
export const PATH_FILL_RULE_OFFSET = 2 as const;
export const PATH_RESERVED_OFFSET = 3 as const;
export const PATH_VERB_COUNT_OFFSET = 4 as const;
export const PATH_POINT_COUNT_OFFSET = 8 as const;
export const PATH_VIEW_BOX_X_OFFSET = 12 as const;
export const PATH_VIEW_BOX_Y_OFFSET = 16 as const;
export const PATH_VIEW_BOX_WIDTH_OFFSET = 20 as const;
export const PATH_VIEW_BOX_HEIGHT_OFFSET = 24 as const;
export const PATH_PAYLOAD_OFFSET = 28 as const;
export const AFFINE_RESOURCE_VARIANT = 1 as const;
export const AFFINE_RESOURCE_FIXED_BYTES = 28 as const;
export const AFFINE_RESOURCE_MINIMUM_BYTES = 28 as const;
export const AFFINE_VERSION_OFFSET = 0 as const;
export const AFFINE_VARIANT_OFFSET = 1 as const;
export const AFFINE_A_OFFSET = 4 as const;
export const AFFINE_B_OFFSET = 8 as const;
export const AFFINE_C_OFFSET = 12 as const;
export const AFFINE_D_OFFSET = 16 as const;
export const AFFINE_E_OFFSET = 20 as const;
export const AFFINE_F_OFFSET = 24 as const;
export const IMAGE_BITMAP_RESOURCE_VARIANT = 1 as const;
export const IMAGE_BITMAP_RESOURCE_FIXED_BYTES = null;
export const IMAGE_BITMAP_RESOURCE_MINIMUM_BYTES = 16 as const;
export const IMAGE_BITMAP_VERSION_OFFSET = 0 as const;
export const IMAGE_BITMAP_VARIANT_OFFSET = 1 as const;
export const IMAGE_BITMAP_WIDTH_OFFSET = 4 as const;
export const IMAGE_BITMAP_HEIGHT_OFFSET = 8 as const;
export const IMAGE_BITMAP_PIXEL_BYTES_OFFSET = 12 as const;
export const IMAGE_BITMAP_PIXELS_OFFSET = 16 as const;
export const VIDEO_FRAME_RESOURCE_VARIANT = 1 as const;
export const VIDEO_FRAME_RESOURCE_FIXED_BYTES = null;
export const VIDEO_FRAME_RESOURCE_MINIMUM_BYTES = 16 as const;
export const VIDEO_FRAME_VERSION_OFFSET = 0 as const;
export const VIDEO_FRAME_VARIANT_OFFSET = 1 as const;
export const VIDEO_FRAME_WIDTH_OFFSET = 4 as const;
export const VIDEO_FRAME_HEIGHT_OFFSET = 8 as const;
export const VIDEO_FRAME_POSTER_PIXEL_BYTES_OFFSET = 12 as const;
export const VIDEO_FRAME_POSTER_PIXELS_OFFSET = 16 as const;
export const COMPUTED_STYLE_RESOURCE_VARIANT = 1 as const;
export const COMPUTED_STYLE_RESOURCE_FIXED_BYTES = null;
export const COMPUTED_STYLE_RESOURCE_MINIMUM_BYTES = 16 as const;
export const COMPUTED_STYLE_VERSION_OFFSET = 0 as const;
export const COMPUTED_STYLE_VARIANT_OFFSET = 1 as const;
export const COMPUTED_STYLE_FEATURE_BITS_OFFSET = 4 as const;
export const COMPUTED_STYLE_ENTRY_COUNT_OFFSET = 8 as const;
export const COMPUTED_STYLE_PAYLOAD_BYTES_OFFSET = 12 as const;
export const COMPUTED_STYLE_PAYLOAD_OFFSET = 16 as const;
export const STYLED_RUNS_RESOURCE_VARIANT = 1 as const;
export const STYLED_RUNS_RESOURCE_FIXED_BYTES = null;
export const STYLED_RUNS_RESOURCE_MINIMUM_BYTES = 8 as const;
export const STYLED_RUNS_VERSION_OFFSET = 0 as const;
export const STYLED_RUNS_VARIANT_OFFSET = 1 as const;
export const STYLED_RUNS_RUN_COUNT_OFFSET = 4 as const;
export const STYLED_RUNS_RUNS_OFFSET = 8 as const;

export enum RecordingRecordKind {
  Mutation = 1,
  Input = 2,
  SystemTextMetrics = 3,
  AnimationFrame = 4,
}

export enum VirtualAxis {
  X = 0,
  Y = 1,
}

export enum MutationOpcode {
  CreateNode = 1,
  RemoveNode = 2,
  Reparent = 3,
  SetF32 = 16,
  SetVec4 = 17,
  SetRef = 18,
  SetFlags = 19,
  ClearProp = 20,
  SetTextRun = 32,
  SetRichText = 33,
  DefineResource = 48,
  ReleaseResource = 49,
  ScrollTo = 64,
  ConfigureVirtualList = 65,
  SetVirtualItem = 66,
  ConfigureEditable = 80,
  ConfigureDocument = 97,
  ObserveGeometry = 96,
  Commit = 240,
}

export const MUTATION_LAYOUTS = {
  [MutationOpcode.CreateNode]: { fixedBytes: 20, minimumBytes: 20 },
  [MutationOpcode.RemoveNode]: { fixedBytes: 8, minimumBytes: 8 },
  [MutationOpcode.Reparent]: { fixedBytes: 16, minimumBytes: 16 },
  [MutationOpcode.SetF32]: { fixedBytes: 16, minimumBytes: 16 },
  [MutationOpcode.SetVec4]: { fixedBytes: 28, minimumBytes: 28 },
  [MutationOpcode.SetRef]: { fixedBytes: 16, minimumBytes: 16 },
  [MutationOpcode.SetFlags]: { fixedBytes: 16, minimumBytes: 16 },
  [MutationOpcode.ClearProp]: { fixedBytes: 12, minimumBytes: 12 },
  [MutationOpcode.SetTextRun]: { fixedBytes: 16, minimumBytes: 16 },
  [MutationOpcode.SetRichText]: { fixedBytes: 20, minimumBytes: 20 },
  [MutationOpcode.DefineResource]: { fixedBytes: null, minimumBytes: 16 },
  [MutationOpcode.ReleaseResource]: { fixedBytes: 8, minimumBytes: 8 },
  [MutationOpcode.ScrollTo]: { fixedBytes: 20, minimumBytes: 20 },
  [MutationOpcode.ConfigureVirtualList]: { fixedBytes: 32, minimumBytes: 32 },
  [MutationOpcode.SetVirtualItem]: { fixedBytes: 12, minimumBytes: 12 },
  [MutationOpcode.ConfigureEditable]: { fixedBytes: 24, minimumBytes: 24 },
  [MutationOpcode.ConfigureDocument]: { fixedBytes: 20, minimumBytes: 20 },
  [MutationOpcode.ObserveGeometry]: { fixedBytes: 12, minimumBytes: 12 },
  [MutationOpcode.Commit]: { fixedBytes: 8, minimumBytes: 8 },
} as const;

export enum InputOpcode {
  Replace = 1,
  Insert = 2,
  DeleteBackward = 3,
  DeleteForward = 4,
  SetSelection = 5,
  BeginComposition = 6,
  UpdateComposition = 7,
  CommitComposition = 8,
  CancelComposition = 9,
  Undo = 10,
  Redo = 11,
  FocusEditable = 12,
  BlurEditable = 13,
  RequestCharacterBounds = 14,
  PlaceCaret = 15,
  SetWordBoundaries = 17,
  SetMarks = 18,
  SetPendingMark = 19,
  BreakUndoGroup = 20,
  MoveCaret = 16,
  SetDocumentSelection = 21,
  MoveDocumentCaret = 22,
  EditDocument = 23,
  ScrollBegin = 32,
  ScrollDelta = 33,
  ScrollEnd = 34,
  ScrollCancel = 35,
  SetScrollVelocity = 36,
  ScrollTo = 37,
  ScrollBy = 38,
  DispatchEvent = 48,
  SetPointerCapture = 49,
  ReleasePointerCapture = 50,
  FocusNode = 51,
  BlurNode = 52,
  ResetInteraction = 53,
  DispatchKeyEvent = 54,
  Commit = 240,
}

export const INPUT_LAYOUTS = {
  [InputOpcode.Replace]: { fixedBytes: null, minimumBytes: 28 },
  [InputOpcode.Insert]: { fixedBytes: null, minimumBytes: 20 },
  [InputOpcode.DeleteBackward]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.DeleteForward]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.SetSelection]: { fixedBytes: 28, minimumBytes: 28 },
  [InputOpcode.BeginComposition]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.UpdateComposition]: { fixedBytes: null, minimumBytes: 20 },
  [InputOpcode.CommitComposition]: { fixedBytes: null, minimumBytes: 24 },
  [InputOpcode.CancelComposition]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.Undo]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.Redo]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.FocusEditable]: { fixedBytes: 8, minimumBytes: 8 },
  [InputOpcode.BlurEditable]: { fixedBytes: 8, minimumBytes: 8 },
  [InputOpcode.RequestCharacterBounds]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.PlaceCaret]: { fixedBytes: 20, minimumBytes: 20 },
  [InputOpcode.SetWordBoundaries]: { fixedBytes: null, minimumBytes: 20 },
  [InputOpcode.SetMarks]: { fixedBytes: 32, minimumBytes: 32 },
  [InputOpcode.SetPendingMark]: { fixedBytes: 28, minimumBytes: 28 },
  [InputOpcode.BreakUndoGroup]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.MoveCaret]: { fixedBytes: 12, minimumBytes: 12 },
  [InputOpcode.SetDocumentSelection]: { fixedBytes: 40, minimumBytes: 40 },
  [InputOpcode.MoveDocumentCaret]: { fixedBytes: 12, minimumBytes: 12 },
  [InputOpcode.EditDocument]: { fixedBytes: null, minimumBytes: 32 },
  [InputOpcode.ScrollBegin]: { fixedBytes: 8, minimumBytes: 8 },
  [InputOpcode.ScrollDelta]: { fixedBytes: 20, minimumBytes: 20 },
  [InputOpcode.ScrollEnd]: { fixedBytes: 8, minimumBytes: 8 },
  [InputOpcode.ScrollCancel]: { fixedBytes: 8, minimumBytes: 8 },
  [InputOpcode.SetScrollVelocity]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.ScrollTo]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.ScrollBy]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.DispatchEvent]: { fixedBytes: 68, minimumBytes: 68 },
  [InputOpcode.SetPointerCapture]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.ReleasePointerCapture]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.FocusNode]: { fixedBytes: 16, minimumBytes: 16 },
  [InputOpcode.BlurNode]: { fixedBytes: 12, minimumBytes: 12 },
  [InputOpcode.ResetInteraction]: { fixedBytes: 12, minimumBytes: 12 },
  [InputOpcode.DispatchKeyEvent]: { fixedBytes: 28, minimumBytes: 28 },
  [InputOpcode.Commit]: { fixedBytes: 8, minimumBytes: 8 },
} as const;

export enum DisplayOpcode {
  Save = 1,
  Restore = 2,
  Transform = 3,
  ClipRect = 4,
  Alpha = 5,
  FillRect = 16,
  FillRRect = 17,
  FillPath = 18,
  StrokePath = 19,
  DrawGlyphRun = 32,
  DrawTextFallback = 33,
  DrawTextInlineFallback = 36,
  FillPlaceholder = 38,
  FillColorRect = 39,
  FillColorRRect = 40,
  FillColorBorder = 41,
  DrawEditorDecoration = 37,
  FillColorShadow = 42,
  FillColorPath = 43,
  StrokeColorPath = 44,
  DrawImage = 34,
  DrawPicture = 35,
}

export const DISPLAY_LAYOUTS = {
  [DisplayOpcode.Save]: { fixedBytes: 4, minimumBytes: 4 },
  [DisplayOpcode.Restore]: { fixedBytes: 4, minimumBytes: 4 },
  [DisplayOpcode.Transform]: { fixedBytes: 28, minimumBytes: 28 },
  [DisplayOpcode.ClipRect]: { fixedBytes: 20, minimumBytes: 20 },
  [DisplayOpcode.Alpha]: { fixedBytes: 8, minimumBytes: 8 },
  [DisplayOpcode.FillRect]: { fixedBytes: 24, minimumBytes: 24 },
  [DisplayOpcode.FillRRect]: { fixedBytes: 40, minimumBytes: 40 },
  [DisplayOpcode.FillPath]: { fixedBytes: 12, minimumBytes: 12 },
  [DisplayOpcode.StrokePath]: { fixedBytes: 24, minimumBytes: 24 },
  [DisplayOpcode.DrawGlyphRun]: { fixedBytes: 24, minimumBytes: 24 },
  [DisplayOpcode.DrawTextFallback]: { fixedBytes: 20, minimumBytes: 20 },
  [DisplayOpcode.DrawTextInlineFallback]: { fixedBytes: null, minimumBytes: 20 },
  [DisplayOpcode.FillPlaceholder]: { fixedBytes: 24, minimumBytes: 24 },
  [DisplayOpcode.FillColorRect]: { fixedBytes: 24, minimumBytes: 24 },
  [DisplayOpcode.FillColorRRect]: { fixedBytes: 40, minimumBytes: 40 },
  [DisplayOpcode.FillColorBorder]: { fixedBytes: 68, minimumBytes: 68 },
  [DisplayOpcode.DrawEditorDecoration]: { fixedBytes: 28, minimumBytes: 28 },
  [DisplayOpcode.FillColorShadow]: { fixedBytes: 52, minimumBytes: 52 },
  [DisplayOpcode.FillColorPath]: { fixedBytes: 12, minimumBytes: 12 },
  [DisplayOpcode.StrokeColorPath]: { fixedBytes: 24, minimumBytes: 24 },
  [DisplayOpcode.DrawImage]: { fixedBytes: 40, minimumBytes: 40 },
  [DisplayOpcode.DrawPicture]: { fixedBytes: 16, minimumBytes: 16 },
} as const;

export enum GlyphResourceOpcode {
  DefineGlyphSpan = 1,
  ReleaseGlyphSpan = 2,
}

export const GLYPH_RESOURCE_LAYOUTS = {
  [GlyphResourceOpcode.DefineGlyphSpan]: { fixedBytes: null, minimumBytes: 24 },
  [GlyphResourceOpcode.ReleaseGlyphSpan]: { fixedBytes: 8, minimumBytes: 8 },
} as const;

export enum SystemTextMetricOpcode {
  UpsertSystemTextMetric = 1,
  ReleaseSystemTextMetric = 2,
}

export const SYSTEM_TEXT_METRIC_LAYOUTS = {
  [SystemTextMetricOpcode.UpsertSystemTextMetric]: { fixedBytes: null, minimumBytes: 32 },
  [SystemTextMetricOpcode.ReleaseSystemTextMetric]: { fixedBytes: 12, minimumBytes: 12 },
} as const;

export enum NodeKind {
  Root = 1,
  Container = 2,
  Text = 3,
  Image = 4,
  EditableText = 5,
  Scroll = 6,
  Video = 7,
}

export enum ResourceKind {
  Utf8String = 1,
  Image = 2,
  Path = 3,
  Font = 4,
  GlyphSpan = 5,
  Paint = 6,
  TextStyle = 7,
  Affine = 8,
  ComputedStyle = 9,
  Animation = 10,
  VideoFrame = 11,
  StyledRuns = 12,
}

export enum Prop {
  Width = 1,
  Height = 2,
  MinWidth = 3,
  MinHeight = 4,
  MaxWidth = 5,
  MaxHeight = 6,
  Padding = 7,
  Direction = 8,
  Gap = 9,
  Color = 16,
  BackgroundColor = 17,
  Opacity = 18,
  Transform = 19,
  Text = 32,
  FontSize = 33,
  Font = 34,
  Image = 35,
  PathStrokeWidth = 38,
  Path = 37,
  VideoFrame = 36,
  OnTap = 48,
  SemanticRole = 64,
  SemanticLabel = 65,
  SemanticValue = 66,
  ComputedStyle = 80,
  Animation = 81,
}

export const enum Invalidation {
  None = 0,
  Layout = 1,
  Paint = 2,
  PaintSelf = 4,
  Hit = 8,
  Semantics = 16,
  Scroll = 32,
}

export const PROP_METADATA = {
  1: { name: "Width", valueType: "f32", resourceKind: null, invalidation: 3 },
  2: { name: "Height", valueType: "f32", resourceKind: null, invalidation: 3 },
  3: { name: "MinWidth", valueType: "f32", resourceKind: null, invalidation: 3 },
  4: { name: "MinHeight", valueType: "f32", resourceKind: null, invalidation: 3 },
  5: { name: "MaxWidth", valueType: "f32", resourceKind: null, invalidation: 3 },
  6: { name: "MaxHeight", valueType: "f32", resourceKind: null, invalidation: 3 },
  7: { name: "Padding", valueType: "vec4", resourceKind: null, invalidation: 3 },
  8: { name: "Direction", valueType: "f32", resourceKind: null, invalidation: 3 },
  9: { name: "Gap", valueType: "f32", resourceKind: null, invalidation: 3 },
  16: { name: "Color", valueType: "ref", resourceKind: ResourceKind.Paint, invalidation: 2 },
  17: {
    name: "BackgroundColor",
    valueType: "ref",
    resourceKind: ResourceKind.Paint,
    invalidation: 2,
  },
  18: { name: "Opacity", valueType: "f32", resourceKind: null, invalidation: 4 },
  19: { name: "Transform", valueType: "ref", resourceKind: ResourceKind.Affine, invalidation: 10 },
  32: { name: "Text", valueType: "ref", resourceKind: ResourceKind.Utf8String, invalidation: 19 },
  33: { name: "FontSize", valueType: "f32", resourceKind: null, invalidation: 3 },
  34: { name: "Font", valueType: "ref", resourceKind: ResourceKind.Font, invalidation: 3 },
  35: { name: "Image", valueType: "ref", resourceKind: ResourceKind.Image, invalidation: 3 },
  38: { name: "PathStrokeWidth", valueType: "f32", resourceKind: null, invalidation: 2 },
  37: { name: "Path", valueType: "ref", resourceKind: ResourceKind.Path, invalidation: 2 },
  36: {
    name: "VideoFrame",
    valueType: "ref",
    resourceKind: ResourceKind.VideoFrame,
    invalidation: 3,
  },
  48: { name: "OnTap", valueType: "ref", resourceKind: null, invalidation: 0 },
  64: {
    name: "SemanticRole",
    valueType: "ref",
    resourceKind: ResourceKind.Utf8String,
    invalidation: 16,
  },
  65: {
    name: "SemanticLabel",
    valueType: "ref",
    resourceKind: ResourceKind.Utf8String,
    invalidation: 16,
  },
  66: {
    name: "SemanticValue",
    valueType: "ref",
    resourceKind: ResourceKind.Utf8String,
    invalidation: 16,
  },
  80: {
    name: "ComputedStyle",
    valueType: "ref",
    resourceKind: ResourceKind.ComputedStyle,
    invalidation: 63,
  },
  81: {
    name: "Animation",
    valueType: "ref",
    resourceKind: ResourceKind.Animation,
    invalidation: 12,
  },
} as const;

export const KEYBOARD_CODES = [
  "KeyA",
  "KeyB",
  "KeyC",
  "KeyD",
  "KeyE",
  "KeyF",
  "KeyG",
  "KeyH",
  "KeyI",
  "KeyJ",
  "KeyK",
  "KeyL",
  "KeyM",
  "KeyN",
  "KeyO",
  "KeyP",
  "KeyQ",
  "KeyR",
  "KeyS",
  "KeyT",
  "KeyU",
  "KeyV",
  "KeyW",
  "KeyX",
  "KeyY",
  "KeyZ",
  "Digit0",
  "Digit1",
  "Digit2",
  "Digit3",
  "Digit4",
  "Digit5",
  "Digit6",
  "Digit7",
  "Digit8",
  "Digit9",
  "Enter",
  "Tab",
  "Space",
  "Backspace",
  "Delete",
  "Escape",
  "Insert",
  "ArrowUp",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
  "Home",
  "End",
  "PageUp",
  "PageDown",
  "ShiftLeft",
  "ShiftRight",
  "ControlLeft",
  "ControlRight",
  "AltLeft",
  "AltRight",
  "MetaLeft",
  "MetaRight",
  "CapsLock",
  "NumLock",
  "ScrollLock",
  "ContextMenu",
  "F1",
  "F2",
  "F3",
  "F4",
  "F5",
  "F6",
  "F7",
  "F8",
  "F9",
  "F10",
  "F11",
  "F12",
  "Backquote",
  "Minus",
  "Equal",
  "BracketLeft",
  "BracketRight",
  "Backslash",
  "Semicolon",
  "Quote",
  "Comma",
  "Period",
  "Slash",
  "IntlBackslash",
  "IntlRo",
  "IntlYen",
  "Numpad0",
  "Numpad1",
  "Numpad2",
  "Numpad3",
  "Numpad4",
  "Numpad5",
  "Numpad6",
  "Numpad7",
  "Numpad8",
  "Numpad9",
  "NumpadAdd",
  "NumpadSubtract",
  "NumpadMultiply",
  "NumpadDivide",
  "NumpadDecimal",
  "NumpadEnter",
  "NumpadEqual",
  "NumpadComma",
  "PrintScreen",
  "Pause",
] as const;

export const KEYBOARD_CODES_BY_NAME: ReadonlyMap<string, number> = new Map(
  KEYBOARD_CODES.map((entry, index) => [entry, index + 1]),
);

export const KEYBOARD_KEY_NAMES = [
  "Enter",
  "Tab",
  "Backspace",
  "Delete",
  "Escape",
  "Insert",
  "Clear",
  "ArrowUp",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
  "Home",
  "End",
  "PageUp",
  "PageDown",
  "Shift",
  "Control",
  "Alt",
  "Meta",
  "AltGraph",
  "CapsLock",
  "NumLock",
  "ScrollLock",
  "ContextMenu",
  "Fn",
  "F1",
  "F2",
  "F3",
  "F4",
  "F5",
  "F6",
  "F7",
  "F8",
  "F9",
  "F10",
  "F11",
  "F12",
  "Copy",
  "Cut",
  "Paste",
  "Undo",
  "Redo",
  "Help",
  "Print",
  "PrintScreen",
  "Pause",
  "ZoomIn",
  "ZoomOut",
  "Process",
  "Dead",
  "Unidentified",
] as const;

export const KEYBOARD_KEY_NAMES_BY_NAME: ReadonlyMap<string, number> = new Map(
  KEYBOARD_KEY_NAMES.map((entry, index) => [entry, index + 1]),
);
export const PICTURE_RESOURCES_MAGIC = 1347440452 as const;
export const MAX_PICTURE_RESOURCES_BYTES = 16777216 as const;
export const MAX_PICTURE_RESOURCE_INSTRUCTIONS = 262144 as const;
export const MAX_PICTURE_RESIDENT_BYTES = 16777216 as const;
export enum PictureResourceOpcode {
  DefinePicture = 1,
  ReleasePicture = 2,
}

export const PICTURE_RESOURCE_LAYOUTS = {
  [PictureResourceOpcode.DefinePicture]: { fixedBytes: null, minimumBytes: 12 },
  [PictureResourceOpcode.ReleasePicture]: { fixedBytes: 8, minimumBytes: 8 },
} as const;

export const NON_PASSIVE_REGION_VERSION = 1 as const;
export const NON_PASSIVE_REGION_HEADER_WORDS = 2 as const;
export const NON_PASSIVE_REGION_RECORD_WORDS = 5 as const;
export const NON_PASSIVE_REGION_HEADER_VERSION_INDEX = 0 as const;
export const NON_PASSIVE_REGION_HEADER_REGION_COUNT_INDEX = 1 as const;
export const NON_PASSIVE_REGION_RECORD_FLAGS_INDEX = 0 as const;
export const NON_PASSIVE_REGION_RECORD_LEFT_BITS_INDEX = 1 as const;
export const NON_PASSIVE_REGION_RECORD_TOP_BITS_INDEX = 2 as const;
export const NON_PASSIVE_REGION_RECORD_RIGHT_BITS_INDEX = 3 as const;
export const NON_PASSIVE_REGION_RECORD_BOTTOM_BITS_INDEX = 4 as const;
export const EDITING_GEOMETRY_VERSION = 1 as const;
export const EDITING_GEOMETRY_HEADER_WORDS = 5 as const;
export const EDITING_GEOMETRY_RECT_WORDS = 4 as const;
export const EDITING_GEOMETRY_CHARACTER_WORDS = 6 as const;
export const EDITING_GEOMETRY_HEADER_VERSION_INDEX = 0 as const;
export const EDITING_GEOMETRY_HEADER_NODE_ID_INDEX = 1 as const;
export const EDITING_GEOMETRY_HEADER_SELECTION_START_INDEX = 2 as const;
export const EDITING_GEOMETRY_HEADER_SELECTION_END_INDEX = 3 as const;
export const EDITING_GEOMETRY_HEADER_CHARACTER_COUNT_INDEX = 4 as const;
export const EDITING_GEOMETRY_RECT_LEFT_BITS_INDEX = 0 as const;
export const EDITING_GEOMETRY_RECT_TOP_BITS_INDEX = 1 as const;
export const EDITING_GEOMETRY_RECT_WIDTH_BITS_INDEX = 2 as const;
export const EDITING_GEOMETRY_RECT_HEIGHT_BITS_INDEX = 3 as const;
export const EDITING_GEOMETRY_CHARACTER_START_INDEX = 0 as const;
export const EDITING_GEOMETRY_CHARACTER_END_INDEX = 1 as const;
export const EDITING_GEOMETRY_CHARACTER_LEFT_BITS_INDEX = 2 as const;
export const EDITING_GEOMETRY_CHARACTER_TOP_BITS_INDEX = 3 as const;
export const EDITING_GEOMETRY_CHARACTER_WIDTH_BITS_INDEX = 4 as const;
export const EDITING_GEOMETRY_CHARACTER_HEIGHT_BITS_INDEX = 5 as const;
export const SEMANTICS_VERSION = 1 as const;
export const SEMANTICS_HEADER_WORDS = 2 as const;
export const SEMANTICS_RECORD_WORDS = 9 as const;
export const SEMANTICS_HEADER_VERSION_INDEX = 0 as const;
export const SEMANTICS_HEADER_NODE_COUNT_INDEX = 1 as const;
export const SEMANTICS_RECORD_NODE_ID_INDEX = 0 as const;
export const SEMANTICS_RECORD_FLAGS_INDEX = 1 as const;
export const SEMANTICS_RECORD_LEFT_BITS_INDEX = 2 as const;
export const SEMANTICS_RECORD_TOP_BITS_INDEX = 3 as const;
export const SEMANTICS_RECORD_WIDTH_BITS_INDEX = 4 as const;
export const SEMANTICS_RECORD_HEIGHT_BITS_INDEX = 5 as const;
export const SEMANTICS_RECORD_ROLE_BYTES_INDEX = 6 as const;
export const SEMANTICS_RECORD_LABEL_BYTES_INDEX = 7 as const;
export const SEMANTICS_RECORD_VALUE_BYTES_INDEX = 8 as const;
export const PAINTED_TEXT_VERSION = 1 as const;
export const PAINTED_TEXT_HEADER_WORDS = 3 as const;
export const PAINTED_TEXT_RECORD_WORDS = 5 as const;
export const PAINTED_TEXT_HEADER_VERSION_INDEX = 0 as const;
export const PAINTED_TEXT_HEADER_FLAGS_INDEX = 1 as const;
export const PAINTED_TEXT_HEADER_RECORD_COUNT_INDEX = 2 as const;
export const PAINTED_TEXT_RECORD_NODE_ID_INDEX = 0 as const;
export const PAINTED_TEXT_RECORD_FLAGS_INDEX = 1 as const;
export const PAINTED_TEXT_RECORD_X_BITS_INDEX = 2 as const;
export const PAINTED_TEXT_RECORD_Y_BITS_INDEX = 3 as const;
export const PAINTED_TEXT_RECORD_TEXT_BYTES_INDEX = 4 as const;
export const PAINTED_TEXT_CHANNEL_MASK = 3 as const;
export const PAINTED_TEXT_CHANNEL_SHAPED_RUN = 0 as const;
export const PAINTED_TEXT_CHANNEL_SYSTEM_FALLBACK = 1 as const;
export const PAINTED_TEXT_CHANNEL_INLINE_FALLBACK = 2 as const;
export const PAINTED_TEXT_FLAG_ORIGIN_CLIPPED = 4 as const;
export const PAINTED_TEXT_FLAG_UNATTRIBUTED = 8 as const;
export const PAINTED_TEXT_HEADER_FLAG_TRUNCATED = 1 as const;
export const LAYOUT_GEOMETRY_VERSION = 1 as const;
export const LAYOUT_GEOMETRY_HEADER_WORDS = 3 as const;
export const LAYOUT_GEOMETRY_RECORD_WORDS = 10 as const;
export const LAYOUT_GEOMETRY_HEADER_VERSION_INDEX = 0 as const;
export const LAYOUT_GEOMETRY_HEADER_FRAME_SEQ_INDEX = 1 as const;
export const LAYOUT_GEOMETRY_HEADER_RECORD_COUNT_INDEX = 2 as const;
export const LAYOUT_GEOMETRY_RECORD_NODE_ID_INDEX = 0 as const;
export const LAYOUT_GEOMETRY_RECORD_FLAGS_INDEX = 1 as const;
export const LAYOUT_GEOMETRY_RECORD_OWN_LEFT_BITS_INDEX = 2 as const;
export const LAYOUT_GEOMETRY_RECORD_OWN_TOP_BITS_INDEX = 3 as const;
export const LAYOUT_GEOMETRY_RECORD_OWN_WIDTH_BITS_INDEX = 4 as const;
export const LAYOUT_GEOMETRY_RECORD_OWN_HEIGHT_BITS_INDEX = 5 as const;
export const LAYOUT_GEOMETRY_RECORD_CLIP_LEFT_BITS_INDEX = 6 as const;
export const LAYOUT_GEOMETRY_RECORD_CLIP_TOP_BITS_INDEX = 7 as const;
export const LAYOUT_GEOMETRY_RECORD_CLIP_WIDTH_BITS_INDEX = 8 as const;
export const LAYOUT_GEOMETRY_RECORD_CLIP_HEIGHT_BITS_INDEX = 9 as const;
export const MAX_OBSERVED_GEOMETRY_NODES = 64 as const;
export const EDIT_TRANSACTIONS_MAGIC = 1162891076 as const;
export const MAX_EDIT_TRANSACTIONS_BYTES = 16777216 as const;
export const MAX_EDIT_TRANSACTION_INSTRUCTIONS = 262144 as const;
export enum EditTransactionOpcode {
  DocumentSelection = 3,
  Structure = 2,
  Transaction = 1,
}

export const EDIT_TRANSACTION_LAYOUTS = {
  [EditTransactionOpcode.DocumentSelection]: { fixedBytes: 32, minimumBytes: 32 },
  [EditTransactionOpcode.Structure]: { fixedBytes: null, minimumBytes: 32 },
  [EditTransactionOpcode.Transaction]: { fixedBytes: null, minimumBytes: 64 },
} as const;

export const EVENT_TRANSACTIONS_MAGIC = 1448103748 as const;
export const MAX_EVENT_TRANSACTIONS_BYTES = 16777216 as const;
export const MAX_EVENT_TRANSACTION_INSTRUCTIONS = 262144 as const;
export enum EventTransactionOpcode {
  Event = 1,
}

export const EVENT_TRANSACTION_LAYOUTS = {
  [EventTransactionOpcode.Event]: { fixedBytes: null, minimumBytes: 92 },
} as const;
